In [1]:
import numpy as np 
import pandas as pd

In [2]:
train_meta_df = pd.read_csv('./petfinder-pawpularity-score/train.csv')
test_meta_df = pd.read_csv('./petfinder-pawpularity-score/test.csv')

In [4]:
print(f'{train_meta_df.shape} - Train\n{test_meta_df.shape} - Test')

(9912, 14) - Train
(8, 13) - Test

In [5]:
train_meta_df.dtypes

Id               object
Subject Focus     int64
Eyes              int64
Face              int64
Near              int64
Action            int64
Accessory         int64
Group             int64
Collage           int64
Human             int64
Occlusion         int64
Info              int64
Blur              int64
Pawpularity       int64
dtype: object

In [6]:
train_meta_df.head()

,Id,Subject Focus,Eyes,Face,Near,Action,Accessory,Group,Collage,Human,Occlusion,Info,Blur,Pawpularity
0,0007de18844b0dbbb5e1f607da0606e0,0,1,1,1,0,0,1,0,0,0,0,0,63
1,0009c66b9439883ba2750fb825e1d7db,0,1,1,0,0,0,0,0,0,0,0,0,42
2,0013fd999caf9a3efe1352ca1b0d937e,0,1,1,1,0,0,0,0,1,1,0,0,28
3,0018df346ac9c1d8413cfcc888ca8246,0,1,1,1,0,0,0,0,0,0,0,0,15
4,001dc955e10590d3ca4673f034feeef2,0,0,0,1,0,0,1,0,0,0,0,0,72

In [7]:
test_meta_df.head()

,Id,Subject Focus,Eyes,Face,Near,Action,Accessory,Group,Collage,Human,Occlusion,Info,Blur
0,4128bae22183829d2b5fea10effdb0c3,1,0,1,0,0,1,1,0,0,1,0,1
1,43a2262d7738e3d420d453815151079e,0,1,0,0,0,0,1,1,0,0,0,0
2,4e429cead1848a298432a0acad014c9d,0,0,0,1,0,1,1,1,0,1,1,1
3,80bc3ccafcc51b66303c2c263aa38486,1,0,1,0,0,0,0,0,0,0,1,0
4,8f49844c382931444e68dffbe20228f4,1,1,1,0,1,1,0,1,0,1,1,0

In [8]:
submisson = pd.read_csv('./petfinder-pawpularity-score/sample_submission.csv')
test_meta_sample_y = submisson['Pawpularity']
submisson.head()

                                 Id  Pawpularity
0  4128bae22183829d2b5fea10effdb0c3        67.75
1  43a2262d7738e3d420d453815151079e        59.15
2  4e429cead1848a298432a0acad014c9d        20.02
3  80bc3ccafcc51b66303c2c263aa38486        94.53
4  8f49844c382931444e68dffbe20228f4        89.82

In [9]:
X = train_meta_df.drop(columns=['Id', 'Pawpularity'])
y = train_meta_df['Pawpularity']

In [10]:
train_meta_df_pred = train_meta_df.copy()

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestRegressor

In [12]:
rf_model = RandomForestRegressor(
    n_estimators = 300,
    max_depth = 15,
    random_state = 100,
    verbose = 2
)
rf_model.fit(X, y)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s

building tree 1 of 300
building tree 2 of 300
building tree 3 of 300
building tree 4 of 300
building tree 5 of 300
building tree 6 of 300
building tree 7 of 300
building tree 8 of 300
building tree 9 of 300
building tree 10 of 300
building tree 11 of 300
building tree 12 of 300
building tree 13 of 300
building tree 14 of 300
building tree 15 of 300
building tree 16 of 300
building tree 17 of 300
building tree 18 of 300
building tree 19 of 300
building tree 20 of 300
building tree 21 of 300
building tree 22 of 300
building tree 23 of 300
building tree 24 of 300
building tree 25 of 300
building tree 26 of 300
building tree 27 of 300
building tree 28 of 300
building tree 29 of 300
building tree 30 of 300
building tree 31 of 300
building tree 32 of 300
building tree 33 of 300
building tree 34 of 300
building tree 35 of 300
building tree 36 of 300
building tree 37 of 300
building tree 38 of 300
building tree 39 of 300
building tree 40 of 300
building tree 41 of 300
building tree 42 of 300
building tree 43 of 300
building tree 44 of 300
building tree 45 of 300
building tree 46 of 300
building tree 47 of 300
building tree 48 of 300
building tree 49 of 300
building tree 50 of 300
building tree 51 of 300
building tree 52 of 300
building tree 53 of 300
building tree 54 of 300
building tree 55 of 300
building tree 56 of 300
building tree 57 of 300
building tree 58 of 300
building tree 59 of 300
building tree 60 of 300
building tree 61 of 300
building tree 62 of 300
building tree 63 of 300
building tree 64 of 300
building tree 65 of 300
building tree 66 of 300
building tree 67 of 300
building tree 68 of 300
building tree 69 of 300
building tree 70 of 300
building tree 71 of 300
building tree 72 of 300
building tree 73 of 300
building tree 74 of 300
building tree 75 of 300
building tree 76 of 300
building tree 77 of 300
building tree 78 of 300
building tree 79 of 300
building tree 80 of 300
building tree 81 of 300
building tree 82 of 300
building tree 83 of 300
building tree 84 of 300
building tree 85 of 300
building tree 86 of 300
building tree 87 of 300
building tree 88 of 300
building tree 89 of 300
building tree 90 of 300
building tree 91 of 300
building tree 92 of 300
building tree 93 of 300
building tree 94 of 300
building tree 95 of 300
building tree 96 of 300
building tree 97 of 300
building tree 98 of 300
building tree 99 of 300
building tree 100 of 300
building tree 101 of 300
building tree 102 of 300
building tree 103 of 300
building tree 104 of 300
building tree 105 of 300
building tree 106 of 300
building tree 107 of 300
building tree 108 of 300
building tree 109 of 300
building tree 110 of 300
building tree 111 of 300
building tree 112 of 300
building tree 113 of 300
building tree 114 of 300
building tree 115 of 300
building tree 116 of 300
building tree 117 of 300
building tree 118 of 300
building tree 119 of 300
building tree 120 of 300
building tree 121 of 300
building tree 122 of 300
building tree 123 of 300
building tree 124 of 300
building tree 125 of 300
building tree 126 of 300
building tree 127 of 300
building tree 128 of 300
building tree 129 of 300
building tree 130 of 300
building tree 131 of 300
building tree 132 of 300
building tree 133 of 300
building tree 134 of 300
building tree 135 of 300
building tree 136 of 300
building tree 137 of 300
building tree 138 of 300
building tree 139 of 300
building tree 140 of 300
building tree 141 of 300
building tree 142 of 300
building tree 143 of 300
building tree 144 of 300
building tree 145 of 300
building tree 146 of 300
building tree 147 of 300
building tree 148 of 300
building tree 149 of 300
building tree 150 of 300
building tree 151 of 300
building tree 152 of 300
building tree 153 of 300
building tree 154 of 300
building tree 155 of 300
building tree 156 of 300
building tree 157 of 300
building tree 158 of 300
building tree 159 of 300
building tree 160 of 300
building tree 161 of 300
building tree 162 of 300
building tree 163 of 300
building tree 164 of 300
building tree 165 of 300
building tree 166 of 300
building tree 167 of 300
building tree 168 of 300
building tree 169 of 300
building tree 170 of 300
building tree 171 of 300
building tree 172 of 300
building tree 173 of 300
building tree 174 of 300
building tree 175 of 300
building tree 176 of 300
building tree 177 of 300
building tree 178 of 300
building tree 179 of 300
building tree 180 of 300
building tree 181 of 300
building tree 182 of 300
building tree 183 of 300
building tree 184 of 300
building tree 185 of 300
building tree 186 of 300
building tree 187 of 300
building tree 188 of 300
building tree 189 of 300
building tree 190 of 300
building tree 191 of 300
building tree 192 of 300
building tree 193 of 300
building tree 194 of 300
building tree 195 of 300
building tree 196 of 300
building tree 197 of 300
building tree 198 of 300
building tree 199 of 300
building tree 200 of 300
building tree 201 of 300
building tree 202 of 300
building tree 203 of 300
building tree 204 of 300
building tree 205 of 300
building tree 206 of 300
building tree 207 of 300
building tree 208 of 300
building tree 209 of 300
building tree 210 of 300
building tree 211 of 300
building tree 212 of 300
building tree 213 of 300
building tree 214 of 300
building tree 215 of 300
building tree 216 of 300
building tree 217 of 300
building tree 218 of 300
building tree 219 of 300
building tree 220 of 300
building tree 221 of 300
building tree 222 of 300
building tree 223 of 300
building tree 224 of 300
building tree 225 of 300
building tree 226 of 300
building tree 227 of 300
building tree 228 of 300
building tree 229 of 300
building tree 230 of 300
building tree 231 of 300
building tree 232 of 300
building tree 233 of 300
building tree 234 of 300
building tree 235 of 300
building tree 236 of 300
building tree 237 of 300
building tree 238 of 300
building tree 239 of 300
building tree 240 of 300
building tree 241 of 300
building tree 242 of 300
building tree 243 of 300
building tree 244 of 300
building tree 245 of 300
building tree 246 of 300
building tree 247 of 300
building tree 248 of 300
building tree 249 of 300
building tree 250 of 300
building tree 251 of 300
building tree 252 of 300
building tree 253 of 300
building tree 254 of 300
building tree 255 of 300
building tree 256 of 300
building tree 257 of 300
building tree 258 of 300
building tree 259 of 300
building tree 260 of 300
building tree 261 of 300
building tree 262 of 300
building tree 263 of 300
building tree 264 of 300
building tree 265 of 300
building tree 266 of 300
building tree 267 of 300
building tree 268 of 300
building tree 269 of 300
building tree 270 of 300
building tree 271 of 300
building tree 272 of 300
building tree 273 of 300
building tree 274 of 300
building tree 275 of 300
building tree 276 of 300
building tree 277 of 300
building tree 278 of 300
building tree 279 of 300
building tree 280 of 300
building tree 281 of 300
building tree 282 of 300
building tree 283 of 300
building tree 284 of 300
building tree 285 of 300
building tree 286 of 300
building tree 287 of 300
building tree 288 of 300
building tree 289 of 300
building tree 290 of 300
building tree 291 of 300
building tree 292 of 300
building tree 293 of 300
building tree 294 of 300
building tree 295 of 300
building tree 296 of 300
building tree 297 of 300
building tree 298 of 300
building tree 299 of 300
building tree 300 of 300

[Parallel(n_jobs=1)]: Done 300 out of 300 | elapsed:    1.2s finished

RandomForestRegressor(max_depth=15, n_estimators=300, random_state=100,
                      verbose=2)

In [13]:
rf_train_y_pred = rf_model.predict(X)
rf_test_y_pred = rf_model.predict(test_meta_df.drop(columns=['Id']))

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 300 out of 300 | elapsed:    0.1s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 300 out of 300 | elapsed:    0.0s finished

In [14]:
train_meta_df_pred['RFTrainPred'] = rf_train_y_pred
train_meta_df_pred[['Id', 'Pawpularity', 'RFTrainPred']]

                                    Id  Pawpularity  RFTrainPred
0     0007de18844b0dbbb5e1f607da0606e0           63    36.648311
1     0009c66b9439883ba2750fb825e1d7db           42    37.757958
2     0013fd999caf9a3efe1352ca1b0d937e           28    37.728002
3     0018df346ac9c1d8413cfcc888ca8246           15    37.958315
4     001dc955e10590d3ca4673f034feeef2           72    41.130362
...                                ...          ...          ...
9907  ffbfa0383c34dc513c95560d6e1fdb57           15    30.862276
9908  ffcc8532d76436fc79e50eb2e5238e45           70    37.958315
9909  ffdf2e8673a1da6fb80342fa3b119a20           20    37.728002
9910  fff19e2ce11718548fa1c5d039a5192a           20    38.821704
9911  fff8e47c766799c9e12f3cb3d66ad228           30    37.958315

[9912 rows x 3 columns]

In [15]:
rf_train_RMSE = mean_squared_error(train_meta_df_pred['Pawpularity'], rf_train_y_pred, squared=False)
rf_test_RMSE = mean_squared_error(test_meta_sample_y, rf_test_y_pred, squared=False)

print('RF Train RMSE: ', rf_train_RMSE)
print('RF Test RMSE: ', rf_test_RMSE)

RF Train RMSE:  20.296878746949748
RF Test RMSE:  39.26106319997433

In [16]:
from sklearn.ensemble import AdaBoostRegressor

In [17]:
adab_model = AdaBoostRegressor(
    n_estimators = 10,
    learning_rate = 0.0001,
    loss = 'square',
    random_state = 100
)

adab_model.fit(X, y)

AdaBoostRegressor(learning_rate=0.0001, loss='square', n_estimators=10,
                  random_state=100)

In [18]:
adab_train_y_pred = adab_model.predict(X)
adab_test_y_pred = adab_model.predict(test_meta_df.drop(columns=['Id']))

In [19]:
train_meta_df_pred['ADABTrainPred'] = adab_train_y_pred
train_meta_df_pred[['Id', 'Pawpularity', 'RFTrainPred', 'ADABTrainPred']]

,Id,Pawpularity,RFTrainPred,ADABTrainPred
0,0007de18844b0dbbb5e1f607da0606e0,63,36.648311,38.027628
1,0009c66b9439883ba2750fb825e1d7db,42,37.757958,38.027628
2,0013fd999caf9a3efe1352ca1b0d937e,28,37.728002,38.027628
3,0018df346ac9c1d8413cfcc888ca8246,15,37.958315,38.027628
4,001dc955e10590d3ca4673f034feeef2,72,41.130362,39.305333
...,...,...,...,...
9907,ffbfa0383c34dc513c95560d6e1fdb57,15,30.862276,32.184211
9908,ffcc8532d76436fc79e50eb2e5238e45,70,37.958315,38.027628
9909,ffdf2e8673a1da6fb80342fa3b119a20,20,37.728002,38.027628
9910,fff19e2ce11718548fa1c5d039a5192a,20,38.821704,38.027628
9911,fff8e47c766799c9e12f3cb3d66ad228,30,37.958315,38.027628

In [20]:
adab_train_RMSE = mean_squared_error(train_meta_df['Pawpularity'], adab_train_y_pred, squared=False)
adab_test_RMSE = mean_squared_error(test_meta_sample_y, adab_test_y_pred, squared=False)

print('ADAB Train RMSE: ', adab_train_RMSE)
print('ADAB Test RMSE: ', adab_test_RMSE)

ADAB Train RMSE:  20.553749228749112
ADAB Test RMSE:  35.935700770989655